# Generated by Django 4.2.7 on 2025-05-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191020_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'in draft'), ('published', 'published')], default='draft', max_length=20),
        ),
    ]
